---
#
# Setup required repositories
#
- name: APT | Prepare Sury repository
  import_tasks: setup-repositories.yml
  when: ansible_facts['os_family'] == 'Debian' and php_fpm_sury_repository_enabled

#
# Setup all required packages
#
- name: APT | Updating the apt cache
  apt:
    update_cache: yes

- name: APT | Setting up php packages (non cli only mode)
  apt:
    name: "{{ php_fpm_packages }}"
    state: "{{ php_fpm_packages_mode }}"
  notify: restart php-fpm
  when: php_fpm_enabled and not php_fpm_cli_only

- name: APT | Setting up php packages (cli only mode)
  apt:
    name: "{{ php_fpm_cli_only_packages }}"
    state: "{{ php_fpm_packages_mode }}"
  when: php_fpm_enabled and php_fpm_cli_only
