---
#
# Setup required repositories: Sury (Debian)
#
- block:
  - name: APT | Install Sury repository prerequisites
    apt:
      name:
        - gnupg
        - ca-certificates
        - apt-transport-https
      state: present

  - name: APT | Import the Sury repository signing key
    apt_key:
      url: https://packages.sury.org/php/apt.gpg
      state: present

  - name: APT | Install the Sury repository
    apt_repository:
      repo: "deb https://packages.sury.org/php/ {{ ansible_facts['distribution_release'] }} main"
      filename: sury-php
      state: present
      update_cache: true

  when: ansible_facts['os_family'] == 'Debian' and php_fpm_sury_repository_enabled
